app:
  message: This is the properties file for the ${spring.application.name} specific to DEV Enveroment

spring:
  datasource:
    url: jdbc:h2:mem:pet
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-concole
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
      sow-sql: true