app:
  message: This is the properties file for the ${spring.application.name} specific to TEST Enveroment

spring:
  datasource:
    url: jdbc:h2:mem:pet
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"